config/routes.rb
TestTracker1::Application.routes.draw do
  resources :import_logs do
    collection { post :import }
  end

  root :to => "import_logs#index"  

  resources :test_results

  resources :test_executions

  resources :test_steps

  resources :test_cases

  resources :use_cases

end

app/models/test_result.rb
class TestResult < ActiveRecord::Base
  belongs_to :test_step
  belongs_to :test_execution
end

app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  before_action :set_test_result, only: [:show, :edit, :update, :destroy]

  # GET /test_results
  # GET /test_results.json
  def index
    @test_results = TestResult.all
  end

  # GET /test_results/1
  # GET /test_results/1.json
  def show
  end

  # GET /test_results/new
  def new
    @test_result = TestResult.new
  end

  # GET /test_results/1/edit
  def edit
  end

  # POST /test_results
  # POST /test_results.json
  def create
    @test_result = TestResult.new(test_result_params)

    respond_to do |format|
      if @test_result.save
        format.html { redirect_to @test_result, notice: 'Test result was successfully created.' }
        format.json { render action: 'show', status: :created, location: @test_result }
      else
        format.html { render action: 'new' }
        format.json { render json: @test_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_results/1
  # PATCH/PUT /test_results/1.json
  def update
    respond_to do |format|
      if @test_result.update(test_result_params)
        format.html { redirect_to @test_result, notice: 'Test result was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @test_result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_results/1
  # DELETE /test_results/1.json
  def destroy
    @test_result.destroy
    respond_to do |format|
      format.html { redirect_to test_results_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_result
      @test_result = TestResult.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_result_params
      params.require(:test_result).permit(:status, :comment)
    end
end

app/helpers/test_results_helper.rb
module TestResultsHelper
end

app/views/test_results/_form.html.erb
<%= form_for(@test_result) do |f| %>
  <% if @test_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_result.errors.count, "error") %> prohibited this test_result from being saved:</h2>

      <ul>
      <% @test_result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_results/edit.html.erb
<h1>Editing test_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_result %> |
<%= link_to 'Back', test_results_path %>

app/views/test_results/index.html.erb
<h1>Listing test_results</h1>

<table>
  <thead>
    <tr>
      <th>Status</th>
      <th>Comment</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @test_results.each do |test_result| %>
      <tr>
        <td><%= test_result.status %></td>
        <td><%= test_result.comment %></td>
        <td><%= link_to 'Show', test_result %></td>
        <td><%= link_to 'Edit', edit_test_result_path(test_result) %></td>
        <td><%= link_to 'Destroy', test_result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test result', new_test_result_path %>

app/views/test_results/new.html.erb
<h1>New test_result</h1>

<%= render 'form' %>

<%= link_to 'Back', test_results_path %>

app/views/test_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @test_result.status %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @test_result.comment %>
</p>

<%= link_to 'Edit', edit_test_result_path(@test_result) %> |
<%= link_to 'Back', test_results_path %>