config/routes.rb
TestTracker1::Application.routes.draw do
  resources :import_logs do
    collection { post :import }
  end

  root :to => "import_logs#index"  

  resources :test_results

  resources :test_executions

  resources :test_steps

  resources :test_cases

  resources :use_cases

end

app/models/test_step.rb
class TestStep < ActiveRecord::Base
  belongs_to  :test_case
  has_many    :test_results
end

app/controllers/test_steps_controller.rb
class TestStepsController < ApplicationController
  before_action :set_test_step, only: [:show, :edit, :update, :destroy]

  # GET /test_steps
  # GET /test_steps.json
  def index
    @test_steps = TestStep.all
  end

  # GET /test_steps/1
  # GET /test_steps/1.json
  def show
  end

  # GET /test_steps/new
  def new
    @test_step = TestStep.new
  end

  # GET /test_steps/1/edit
  def edit
  end

  # POST /test_steps
  # POST /test_steps.json
  def create
    @test_step = TestStep.new(test_step_params)

    respond_to do |format|
      if @test_step.save
        format.html { redirect_to @test_step, notice: 'Test step was successfully created.' }
        format.json { render action: 'show', status: :created, location: @test_step }
      else
        format.html { render action: 'new' }
        format.json { render json: @test_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_steps/1
  # PATCH/PUT /test_steps/1.json
  def update
    respond_to do |format|
      if @test_step.update(test_step_params)
        format.html { redirect_to @test_step, notice: 'Test step was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @test_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_steps/1
  # DELETE /test_steps/1.json
  def destroy
    @test_step.destroy
    respond_to do |format|
      format.html { redirect_to test_steps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_step
      @test_step = TestStep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_step_params
      params[:test_step]
    end
end

app/helpers/test_steps_helper.rb
module TestStepsHelper
end

app/views/test_steps/_form.html.erb
<%= form_for(@test_step) do |f| %>
  <% if @test_step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_step.errors.count, "error") %> prohibited this test_step from being saved:</h2>

      <ul>
      <% @test_step.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_steps/edit.html.erb
<h1>Editing test_step</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_step %> |
<%= link_to 'Back', test_steps_path %>

app/views/test_steps/index.html.erb
<h1>Listing test_steps</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @test_steps.each do |test_step| %>
      <tr>
        <td><%= link_to 'Show', test_step %></td>
        <td><%= link_to 'Edit', edit_test_step_path(test_step) %></td>
        <td><%= link_to 'Destroy', test_step, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test step', new_test_step_path %>

app/views/test_steps/new.html.erb
<h1>New test_step</h1>

<%= render 'form' %>

<%= link_to 'Back', test_steps_path %>

app/views/test_steps/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_test_step_path(@test_step) %> |
<%= link_to 'Back', test_steps_path %>