config/routes.rb
TestTracker1::Application.routes.draw do
  resources :import_logs do
    collection { post :import }
  end

  root :to => "import_logs#index"  

  resources :test_results

  resources :test_executions

  resources :test_steps

  resources :test_cases

  resources :use_cases

end

app/models/import_log.rb
require 'roo'
require 'date'

class ImportLog < ActiveRecord::Base
  def self.import(file)

    log = ImportLog.new
    log.import_date = Time.now 
    log.file_name = File.basename(file.path)
    log.save()


    ss = Roo::Excelx.new(file.path, nil, :ignore)
    ss.sheets.each_with_index do |sheet_name, index|

      #load/create the use case
      current_use_case = UseCase.new #load from db by the name
      current_use_case.name = sheet_name
      current_use_case.save()
  
      #load/create the test execution
      current_test_execution = TestExecution.new
      current_test_execution.date_executed = Date.parse(ss.sheet(index).row(1)[2].to_s)
      current_test_execution.save()
    
      #populate the test cases
      current_test_case = nil
      inside_steps = false
      2.upto(ss.sheet(index).last_row).each do |row_index|
        #find out if we are starting a new test case
        if(ss.sheet(index).row(row_index)[0].to_s.include?("Test Case ID"))
          inside_steps = false
          current_test_case = TestCase.new
          current_test_case.use_case = current_use_case
          current_test_case.case_id = ss.sheet(index).row(row_index)[1]
          puts "test case found"
        elsif(ss.sheet(index).row(row_index)[0].to_s.include?("Test Case Title"))
         current_test_case.case_title = ss.sheet(index).row(row_index)[1]
         #current_test_case.save()
        elsif(ss.sheet(index).row(row_index)[0].to_s.include?("Steps"))
          inside_steps = true
        end
       
        if(inside_steps && ss.sheet(index).row(row_index)[1].to_s != "")
          step = TestStep.new
          step.test_case = current_test_case
          step.step_name = ss.sheet(index).row(row_index)[1].to_s
          step.save()
   
          result = TestResult.new
          result.test_execution = current_test_execution
          result.test_step = step
          result.status = ss.sheet(index).row(row_index)[2].to_s == 'Y'
          result.save()
        end
      end

    end
  end
end

app/controllers/import_logs_controller.rb
class ImportLogsController < ApplicationController
  before_action :set_import_log, only: [:show, :edit, :update, :destroy]

  # GET /import_logs
  # GET /import_logs.json
  def index
    @import_logs = ImportLog.all
  end

  def import
    ImportLog.import(params[:file])
    redirect_to root_url, notice: "File imported"
  end

  # GET /import_logs/1
  # GET /import_logs/1.json
  def show
  end

  # GET /import_logs/new
  def new
    @import_log = ImportLog.new
  end

  # GET /import_logs/1/edit
  def edit
  end

  # POST /import_logs
  # POST /import_logs.json
  def create
    @import_log = ImportLog.new(import_log_params)

    respond_to do |format|
      if @import_log.save
        format.html { redirect_to @import_log, notice: 'Import log was successfully created.' }
        format.json { render action: 'show', status: :created, location: @import_log }
      else
        format.html { render action: 'new' }
        format.json { render json: @import_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /import_logs/1
  # PATCH/PUT /import_logs/1.json
  def update
    respond_to do |format|
      if @import_log.update(import_log_params)
        format.html { redirect_to @import_log, notice: 'Import log was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @import_log.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /import_logs/1
  # DELETE /import_logs/1.json
  def destroy
    @import_log.destroy
    respond_to do |format|
      format.html { redirect_to import_logs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import_log
      @import_log = ImportLog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def import_log_params
      params.require(:import_log).permit(:import_date, :file_name, :file_size)
    end
end

app/helpers/import_logs_helper.rb
module ImportLogsHelper
end

app/views/import_logs/_form.html.erb
<%= form_for(@import_log) do |f| %>
  <% if @import_log.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@import_log.errors.count, "error") %> prohibited this import_log from being saved:</h2>

      <ul>
      <% @import_log.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :import_date %><br>
    <%= f.datetime_select :import_date %>
  </div>
  <div class="field">
    <%= f.label :file_name %><br>
    <%= f.text_field :file_name %>
  </div>
  <div class="field">
    <%= f.label :file_size %><br>
    <%= f.number_field :file_size %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/import_logs/edit.html.erb
<h1>Editing import_log</h1>

<%= render 'form' %>

<%= link_to 'Show', @import_log %> |
<%= link_to 'Back', import_logs_path %>

app/views/import_logs/index.html.erb
<h1>Imports</h1>

<br />
<h2>Import New File</h2>
  <%= form_tag import_import_logs_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import" %>
  <% end %>
<hr />

<table>
  <thead>
    <tr>
      <th>Import date</th>
      <th>File name</th>
      <th>File size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @import_logs.each do |import_log| %>
      <tr>
        <td><%= import_log.import_date %></td>
        <td><%= import_log.file_name %></td>
        <td><%= import_log.file_size %></td>
        <td><%= link_to 'Show', import_log %></td>
        <td><%= link_to 'Edit', edit_import_log_path(import_log) %></td>
        <td><%= link_to 'Destroy', import_log, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Import log', new_import_log_path %>

app/views/import_logs/new.html.erb
<h1>New import_log</h1>

<%= render 'form' %>

<%= link_to 'Back', import_logs_path %>

app/views/import_logs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Import date:</strong>
  <%= @import_log.import_date %>
</p>

<p>
  <strong>File name:</strong>
  <%= @import_log.file_name %>
</p>

<p>
  <strong>File size:</strong>
  <%= @import_log.file_size %>
</p>

<%= link_to 'Edit', edit_import_log_path(@import_log) %> |
<%= link_to 'Back', import_logs_path %>