config/routes.rb
TestTracker1::Application.routes.draw do
  resources :import_logs do
    collection { post :import }
  end

  root :to => "import_logs#index"  

  resources :test_results

  resources :test_executions

  resources :test_steps

  resources :test_cases

  resources :use_cases

end

app/models/test_execution.rb
class TestExecution < ActiveRecord::Base
  has_many :test_results  
end

app/controllers/test_executions_controller.rb
class TestExecutionsController < ApplicationController
  before_action :set_test_execution, only: [:show, :edit, :update, :destroy]

  # GET /test_executions
  # GET /test_executions.json
  def index
    @test_executions = TestExecution.all
  end

  # GET /test_executions/1
  # GET /test_executions/1.json
  def show
  end

  # GET /test_executions/new
  def new
    @test_execution = TestExecution.new
  end

  # GET /test_executions/1/edit
  def edit
  end

  # POST /test_executions
  # POST /test_executions.json
  def create
    @test_execution = TestExecution.new(test_execution_params)

    respond_to do |format|
      if @test_execution.save
        format.html { redirect_to @test_execution, notice: 'Test execution was successfully created.' }
        format.json { render action: 'show', status: :created, location: @test_execution }
      else
        format.html { render action: 'new' }
        format.json { render json: @test_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /test_executions/1
  # PATCH/PUT /test_executions/1.json
  def update
    respond_to do |format|
      if @test_execution.update(test_execution_params)
        format.html { redirect_to @test_execution, notice: 'Test execution was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @test_execution.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /test_executions/1
  # DELETE /test_executions/1.json
  def destroy
    @test_execution.destroy
    respond_to do |format|
      format.html { redirect_to test_executions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_execution
      @test_execution = TestExecution.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_execution_params
      params.require(:test_execution).permit(:date_executed)
    end
end

app/helpers/test_executions_helper.rb
module TestExecutionsHelper
end

app/views/test_executions/_form.html.erb
<%= form_for(@test_execution) do |f| %>
  <% if @test_execution.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@test_execution.errors.count, "error") %> prohibited this test_execution from being saved:</h2>

      <ul>
      <% @test_execution.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_executed %><br>
    <%= f.date_select :date_executed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/test_executions/edit.html.erb
<h1>Editing test_execution</h1>

<%= render 'form' %>

<%= link_to 'Show', @test_execution %> |
<%= link_to 'Back', test_executions_path %>

app/views/test_executions/index.html.erb
<h1>Listing test_executions</h1>

<table>
  <thead>
    <tr>
      <th>Date executed</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @test_executions.each do |test_execution| %>
      <tr>
        <td><%= test_execution.date_executed %></td>
        <td><%= link_to 'Show', test_execution %></td>
        <td><%= link_to 'Edit', edit_test_execution_path(test_execution) %></td>
        <td><%= link_to 'Destroy', test_execution, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Test execution', new_test_execution_path %>

app/views/test_executions/new.html.erb
<h1>New test_execution</h1>

<%= render 'form' %>

<%= link_to 'Back', test_executions_path %>

app/views/test_executions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date executed:</strong>
  <%= @test_execution.date_executed %>
</p>

<%= link_to 'Edit', edit_test_execution_path(@test_execution) %> |
<%= link_to 'Back', test_executions_path %>